;OSoundtracks-SA-Expansion-Sounds-NG

;Example of code designs: it's very similar to SPID but shorter and simpler.

;SoundKey = AnimationKeyName|SoundNameFile|Playback
;SoundEffectKey = MoodName|SoundNameFile|Playback
;SoundPositionKey = PositionKeyword|SoundNameFile|Playback
;SoundTAGKey = TagName|SoundNameFile|Playback
;SoundMenuKey = ModerLister|SoundNameFile|Playback

;AnimationKeyName: Animation event message

;MoodName: Mood state related to the animation (e.g., alegria)

;PositionKeyword: Keyword representing the animation or position (e.g., kiss)

;SoundNameFile: Sound file located at \sound\OSoundtracks\Example.mp3

;Playback: Support for 'loop' and 'once' keywords

;SoundMenuKey: Menu musica


;------------------------------------------------------------------------------------------------------
;------------------------------------------------------------------------------------------------------


;John95acNord
SoundMenuKey = John95acNord|ancient-life|

;John95acNord
SoundMenuKey = John95acNord|enthnic-heaven|

;John95acNord
SoundMenuKey = John95acNord|farewell|

;John95acNord
SoundMenuKey = John95acNord|heilir-sir-norse-viking-background|

;John95acNord
SoundMenuKey = John95acNord|northern-ideas|

;John95acNord
SoundMenuKey = John95acNord|one-last-knight-ride|

;John95acNord
SoundMenuKey = John95acNord|the-gift-pagan-norse-background|

;John95acNord
SoundMenuKey = John95acNord|vikings-chanting-with-percussion|

;John95acNord
SoundMenuKey = John95acNord|where-the-brave-may-live-forever|


