;OSoundtracks-SA-Expansion-Sounds-NG

;Example of code designs: it's very similar to SPID but shorter and simpler.

;SoundKey = AnimationKeyName|SoundNameFile|Playback
;SoundEffectKey = MoodName|SoundNameFile|Playback
;SoundPositionKey = PositionKeyword|SoundNameFile|Playback
;SoundTAGKey = TagName|SoundNameFile|Playback
;SoundMenuKey = ModerLister|SoundNameFile|Playback

;AnimationKeyName: Animation event message

;MoodName: Mood state related to the animation (e.g., alegria)

;PositionKeyword: Keyword representing the animation or position (e.g., kiss)

;SoundNameFile: Sound file located at \sound\OSoundtracks\Example.mp3

;Playback: Support for 'loop' and 'once' keywords

;SoundMenuKey: Menu musica


;------------------------------------------------------------------------------------------------------
;------------------------------------------------------------------------------------------------------


;sleep
SoundPositionKey = sleep|sleeping|loop

;sleep
SoundPositionKey = sleep|sleeping-snoring-breathing|loop

;sleep
SoundPositionKey = sleep|snoring|loop

;sleep
SoundPositionKey = sleep|female-sigh-Sleep|loop

;sleep
SoundPositionKey = sleep|heavy-snoring-sound-effect-deep-sleep-noise|loop

;sleep
SoundPositionKey = sleep|snoring-sound-effect-deep-sleep-breathing|loop

;sleep
SoundPositionKey = sleep|deep-sigh-asmr-let-it-all-out-Sleep|loop

