;OSoundtracks-Expansion-Sounds-SA

;Example of code designs: it's very similar to SPID but shorter and simpler.

;SoundKey = AnimationKeyName|SoundNameFile|Playback

;AnimationKeyName: animation message you'll get it in Ostim.log when going to the animation

;SoundNameFile: sound located in the path \sound\OSoundtracks\Example.wav

;Playback: time in seconds before the new loop starts, leave empty by default - WIP


;ShadowmanBallroombachata
SoundKey = ShadowmanBallroombachata|senorita|

;ShadowmanBallroomballet
SoundKey = ShadowmanBallroomballet|BallroomBalletMusic|

;ShadowmanBallroomsalsa1
SoundKey = ShadowmanBallroomsalsa1|BallroomSalsaMusic|

;ShadowmanBallroomslowfox
SoundKey = ShadowmanBallroomslowfox|Fly Me To The Moon|

;ShadowmanBallroomslowwaltz
SoundKey = ShadowmanBallroomslowwaltz|Cant Help Falling in Love|

;ShadowmanBallroomtango
SoundKey = ShadowmanBallroomtango|Asi Se Baila El Tango|

;ShadowmanBallroomvienese
SoundKey = ShadowmanBallroomvienese|Moje jedyne marzenie|